<Project>

	<PropertyGroup Condition="'$(MSBuildRuntimeType)' == 'Full'">
		<AlwaysCompileMarkupFilesInSeparateDomain>true</AlwaysCompileMarkupFilesInSeparateDomain>
	</PropertyGroup>

	<ItemGroup Condition="'$(EnableDefaultItems)' != 'false'">
		<Compile Remove="obj/**/*AssemblyInfo.cs" />
		<Compile Remove="obj/**/*AssemblyAttributes.cs" />
		<Compile Remove="obj-*/**/*AssemblyInfo.cs" />
		<Compile Remove="obj-*/**/*AssemblyAttributes.cs" />
	</ItemGroup>

</Project>
